[package]
name = "ct2rs"
version = "0.7.3"
authors = ["Junpei Kawamoto <kawamoto.junpei@gmail.com>"]
edition = "2021"
description = "Rust bindings for OpenNMT/CTranslate2"
documentation = "https://docs.rs/ct2rs"
repository = "https://github.com/jkawamoto/ctranslate2-rs"
license = "MIT"
keywords = ["ctranslate2", "bindings", "llm"]
categories = ["api-bindings"]
include = [
    "/include",
    "/src",
    "/build.rs",
    "/LICENSE",
    "/examples",
    "/CTranslate2/CMakeLists.txt",
    "/CTranslate2/LICENSE",
    "/CTranslate2/cmake",
    "/CTranslate2/cpp",
    "/CTranslate2/include",
    "/CTranslate2/python",
    "/CTranslate2/src",
    "/CTranslate2/third_party",
    "!/CTranslate2/**/.*",
    "!/CTranslate2/**/test",
    "!/CTranslate2/**/docs",
    "!/CTranslate2/**/media",
]

[dependencies]
cxx = { version = "1.0.121", features = ["c++17"] }
anyhow = "1.0.82"
tokenizers = "0.19.1"
sentencepiece = "0.11.2"
intel-mkl-src = { version = "0.8.1", optional = true }


[dev-dependencies]
clap = { version = "4.5.4", features = ["derive"] }
rand = "0.8.5"
rsnltk = "0.1.3"


[build-dependencies]
cmake = "0.1.50"
cxx-build = "1.0.121"
walkdir = "2.5.0"


[features]
default = ["ruy", "accelerate"]
mkl = ["dep:intel-mkl-src"]
openblas = []
ruy = []
accelerate = []
cuda = []
cudnn = ["cuda"]


[[example]]
name = "nllb"

[[example]]
name = "marian-mt"

[[example]]
name = "generator"

[[example]]
name = "marian-test"